services:
  tenants-backend:
    image: tenants-app-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenants-backend
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=collaudo
      - DB_HOST=host.docker.internal
      - DB_PORT=3307
      - DB_NAME=QTMTenant
      - DB_USERNAME=root
      - DB_PASSWORD=dago
      - KEYCLOAK_HOST=host.docker.internal
      - KEYCLOAK_PORT=8085
      - KEYCLOAK_REALM=QTM
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - ./logs:/app/logs
    restart: unless-stopped

# Questo file docker-compose è pensato per avviare solo il backend Spring Boot.
# Assicurati che il Dockerfile sia presente nella root e che esponga la porta 8080.
# Modifica SPRING_PROFILES_ACTIVE secondo le tue esigenze.
