server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:QTMTenant_${APP_KEYCLOAK_REALM_CODE}}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
           issuer-uri: ${APP_KEYCLOAK_SERVER_URL:http://localhost:8085}/realms/${APP_KEYCLOAK_REALM_CODE:QTM}

# Configurazione per connessione con QTMTicket
qtm:
  ticket:
    base-url: ${QTM_TICKET_BASE_URL:http://localhost:8084/api/ticket}

