server:
  port: 8087

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:QTMTenant_${APP_KEYCLOAK_REALM_CODE}}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:dago}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/QTM

# Configurazione per connessione con QTMTicket
qtm:
  ticket:
    base-url: ${QTM_TICKET_BASE_URL:http://localhost:8084/api/ticket}

