/**
 * Registro centralizzato dei moduli struttura usati dal frontend per menu, rotte e permessi.
 */
export const STRUCTURE_MODULE_CODES = {
  GENERIC: 'STRUCTURE',
  ASL: 'STRUCTURE-ASL',
  HOSPITAL: 'HOSPITAL',
  HOSPITAL_PHARMACY: 'STRUCTURE-FARMACY-O',
  RETAIL_PHARMACY: 'STRUCTURE-FARMACY-R',
  LOGISTICS_WAREHOUSE: 'STRUCTURE_LOGISTICS_WAREHOUSE',
  MATERIAL_WAREHOUSE: 'STRUCTURE_MATERIAL_WAREHOUSE',
  PHARMA_COMPANY: 'STRUCTURE_PHARMA_COMPANY',
  SPECIALIST_CLINIC: 'STRUCTURE_SPECIALIST_CLINIC',
  BULK_IMPORT: 'STRUCTURE_IMPORT'
} as const;