INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'USER', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'USER', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'USER', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'USER', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'USER', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('APPROVE', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('APPROVE', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('GET_DELETE_CHECK', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('GET_DELETE_CHECK', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('APPROVE', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('APPROVE', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE_IMPORT', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE_IMPORT', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE-ASL', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE-ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE-ASL', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE-ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE-ASL', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE-ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE-ASL', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE-ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE-ASL', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE-ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE-ASL', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE-ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE-ASL', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE-ASL', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE-FARMACY-O', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE-FARMACY-O', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE-FARMACY-O', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE-FARMACY-O', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE-FARMACY-O', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE-FARMACY-O', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE-FARMACY-O', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE-FARMACY-O', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE-FARMACY-O', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE-FARMACY-O', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE-FARMACY-O', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE-FARMACY-O', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE-FARMACY-O', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE-FARMACY-O', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE-FARMACY-R', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE-FARMACY-R', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE-FARMACY-R', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE-FARMACY-R', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE-FARMACY-R', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE-FARMACY-R', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE-FARMACY-R', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE-FARMACY-R', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE-FARMACY-R', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE-FARMACY-R', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE-FARMACY-R', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE-FARMACY-R', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE-FARMACY-R', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE-FARMACY-R', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE_LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE_MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE_MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE_MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE_MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE_MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE_MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE_MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE_MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE_MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE_MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE_MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE_MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE_MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE_MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE_PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE_PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE_PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE_PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE_PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE_PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE_PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE_PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE_PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE_PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE_PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE_PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE_PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE_PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE_SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE_SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE_SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE_SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE_SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE_SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE_SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE_SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE_SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE_SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE_SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE_SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE_SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE_SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT');