-- Seed corrente di function_module_role_authorizations, espresso come INSERT statici.
-- I ruoli SUPER_ADMIN_B e SUPER_ADMIN_B1 sono esclusi esplicitamente come richiesto.

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'USER', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'USER', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'USER', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'USER', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'USER', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'USER', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'PATIENT', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'PATIENT', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('APPROVE', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('APPROVE', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'DOCTOR', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'DOCTOR', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'NURSE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'NURSE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('GET_DELETE_CHECK', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('GET_DELETE_CHECK', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'ROLE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'ROLE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'MODULE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'MODULE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('APPROVE', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('APPROVE', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'FUNCTION', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'FUNCTION', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'STRUCTURE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'ASL', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'ASL', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'ASL', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'ASL', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'ASL', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'ASL', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'ASL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'ASL', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'ASL', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'HOSPITAL', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'HOSPITAL', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'HOSPITAL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'HOSPITAL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'HOSPITAL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'HOSPITAL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'HOSPITAL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'HOSPITAL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'HOSPITAL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'HOSPITAL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'HOSPITAL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'HOSPITAL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'HOSPITAL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'HOSPITAL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'HOSPITAL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'HOSPITAL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'RETAIL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'RETAIL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'RETAIL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'RETAIL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'RETAIL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'RETAIL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'RETAIL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'RETAIL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'RETAIL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'RETAIL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'RETAIL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'RETAIL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'RETAIL_PHARMACY', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'RETAIL_PHARMACY', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'LOGISTICS_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'LOGISTICS_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'MATERIAL_WAREHOUSE', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'MATERIAL_WAREHOUSE', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'PHARMA_COMPANY', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'PHARMA_COMPANY', 'SUPER_ADMIN', 'FULL_EDIT');

INSERT IGNORE INTO function_module_role_authorizations (function_code, module_code, role_id, authorization) VALUES
  ('CREATE', 'SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('CREATE', 'SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('READ', 'SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('READ', 'SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('SEARCH', 'SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('FIND_TYPES', 'SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('FIND_PARENT_OPTIONS', 'SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('UPDATE', 'SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT'),
  ('DELETE', 'SPECIALIST_CLINIC', 'ADMIN', 'FULL_EDIT'),
  ('DELETE', 'SPECIALIST_CLINIC', 'SUPER_ADMIN', 'FULL_EDIT');