server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/QTMTenant?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: dago
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/QTM

logging:
  level:
    root: INFO

qtm:
  dashboard:
    api-base-url: http://localhost:8086/api
